/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mocks from "./mocks";
export type { mocks };
export type { Collector } from "./Collector";
export type { CollectorFactory } from "./CollectorFactory";
export type { CollectorRegistry } from "./CollectorRegistry";
export type { SubscriptionManager } from "./SubscriptionManager";
